### ISSUE TITLE
Missing yii.zip 

### ISSUE THREAD

**Issue by farissalih87** [openeyes/OpenEyes#254] opened 2016-05-21 21:26 UTC
I have installed openeyes  all ways following all instructions 
* in windows using  VBox and Vagrant with oe_installer
* in ubuntu desktop with VBox and Vagrant
* ubuntu server
 but still iam getting  
yii.zip not found 
I noticed that while installing after 
 finish installing  (install-system.sh) successfully 
the script (install-oe.sh) dos not clone the openeyes repo telling this directory exist and start cloning the other modules.
 
please help I am trying to git openeyes installed successfully  since one and half year

**Comment by farissalih87** [comment] 2016-05-23 03:09
After trying with (feature/custom-path) branch of oe_installer  I got common.php not fount 
i tried to fix it by coping from local.sample and run (oe-mirate) finished successfully but when I browse the IP address I get the Apache default page 
![oe_4042](https://cloud.githubusercontent.com/assets/12017676/15459336/d0388940-20ac-11e6-947d-0aad84ac12b4.jpg)
![oe_404](https://cloud.githubusercontent.com/assets/12017676/15459337/d043c85a-20ac-11e6-88ed-a372651bf0e2.jpg)

**Comment by splatEric** [comment] 2016-05-24 13:26
I would suggest you take a look at the oe_installer project and see if you can get up and running with it from there. There are still some issues that are being worked on around that, but currently that is probably your best bet:

https://github.com/openeyes/oe_installer

**Comment by splatEric** [comment] 2016-05-24 14:05
I'm so sorry @farissalih87 I just realised in your second post you do mention that you are already using oe_installer ... looking at your screenshot, I'm assuming you are on windows. 

It looks as though the issue is with creating symbolic links. Sadly I'm no expert when it comes to windows, but I have done a bit of googling and one thing to check is whether you have administrative privileges as this is apparently required.

**Comment by antonypenn** [comment] 2016-05-24 14:10
It looks like someone has broken the installer script, as this used to work. It looks like it is not copying the .zip files from the /vagrant/installer/ directory during a fresh install. I will see if I can get fix it.

**Comment by farissalih87** [comment] 2016-05-25 11:02
I hope you can find out what is wrong 
#Note that common.php is also moved from local to local.sample and that's making some problems

**Comment by farissalih87** [comment] 2016-05-25 11:02
I hope you can find out what is wrong 
#Note that common.php is also moved from local to local.sample and that's making some problems

**Comment by splatEric** [comment] 2016-05-25 11:20
The change to common.php is deliberate - having the local config committed causes all sorts of problems when you want to make adjustments to your local instance. The install process should be copying it into place automatically, but looking at the code I am not sure that is actually happening at the moment.

**Comment by biskyt** [comment] 2016-05-27 15:28
I have fixed the installer. Try again now. It was a problem in oe-checkout. Make sure to update the dev tools first by running /vagrant/installer/update-oe-tools.sh, then re-run install-oe.sh

**Closed by biskyt** 2016-05-27 15:28 UTC

**Comment by farissalih87** [comment] 2016-05-29 12:56
installed successfully thanks
